language: python
python:
- '3.6'
before_script:
- yes | python setup.py install
- git clone https://github.com/uc-cdis/dictionaryutils; cd dictionaryutils
script:
- "./run_tests.sh"
deploy:
  provider: s3
  access_key_id: AKIAZRNPHKJIJPXDWO53
  secret_access_key:
    secure: lvfu2w7D4pdhwdgTy+AOHbDJC93QAOMD0F2APEohJbTfeg6/r7bDP9kgoAAUXPs0nhQKOTeTnykA2fXsJJvR+T/yeDGUAAnzm6K6ObAnqohHbjQHmTtf1JwlX1V7K+LrpuUs/6zefzGB39i44Caaq/QWYrNf3a56XxpUflpzEBG4jvD8r4At5eGUspt3gRKRzYZiWDlnGRab7rR5bZ8AUXfXPtwtA0WBl1k+RHNabXhwfmWtc1/Hr13pW3jmsJJAGEnL2G8uvW257BYUxtrbRuImyXyPQ43EgkGa0uROYk5640ZJYJr+ZK7wnsKs+ZE0Mn9Lm0Iug9fqY0ANo2yawnxykHmbYMFo6R3ufKcvx2MGkaQ2xAxfyWetj9NEXzauCM/XrI/gjQtAXoxBsCqLsQcbOwXI0JY51fIIXBhmD9oq7j+P74jo68pY7YpO2WuxtI6kvk1LDSX2CZwZVI6udyI8IR8s+wgZIKwC/EFYrqi7ui+t3Npw/vQPzO2ITHxQJgc6TQ3NMRmJx4BQJvBAtZnhSCortmiSFbMsH5lzIJW8D4F/MjHeYZGdrbI/otiHyzjAeXcCgu5pY4hLQJDgxLbzPJZiL7ovBt1r7qniIbJFs4ESNiYGqNLfrYAvYBoSPse8bTJSkU/XwFw/1a4K8KPloRL0AUwGsafeeZ0mzXA=
  bucket: dictionary-artifacts
  local-dir: artifacts
  upload-dir: covid19-datadictionary/$TRAVIS_BRANCH
  skip_cleanup: true
  on:
    repo: uc-cdis/covid19_datadictionary
    all_branches: true
